#pragma once

/* File generated by cmake -- do not edit. */

#define TecplotMajorVer 2019
#define TecplotMinorVer 1
#define TecplotMajorRev 0
#define TecplotMinorRev 98642
#define TecVersionId "2019.1.0.98642"

#define TecplotSDKBinaryFileVersion 112

#define TecplotAPIVersion 141
#define TecplotAPIVersionStr "141"


